In [16]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(40 ,101, size=(50,5))
#print(type(scores))
#print(scores.shape)
#scores
scores_df= pd.DataFrame(scores,
            index=range(1,51),
            columns=['國文','英文','數學','地理','歷史'])
#scores_df.T #樞紐分析
names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']]= names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名','性別','國文','英文','數學','地理','歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  54  55  61  44  75
7   謝欣蓉  女  47  73  75  47  60
8   羅淑芬  女  86  71  80  82  46
9   許美慧  女  55  78  54  68  64
10  廖志豪  男  59  44  56  47  53

In [22]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60")

     姓名 性別  國文  英文  數學  地理  歷史
7   謝欣蓉  女  47  73  75  47  60
9   許美慧  女  55  78  54  68  64
13  蘇雅婷  女  40  68  87  74  79
19  呂婉慧  女  42  56  92  96  68
27  江雅琪  女  57  76  75  73  74
29  簡婉慧  女  55  56  67  86  72
48  劉婉婷  女  59  76  41  80  69

In [24]:
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df["總分"].rank(ascending=False,method='min')
scores_df.sort_values(by='排名')

     姓名 性別   國文  英文   數學  地理  歷史   總分    平均    排名
39  彭美慧  女   82  92   97  71  98  440  88.0   1.0
35  劉浩然  男   91  83   54  93  96  417  83.4   2.0
34  簡建宏  男   97  90   69  63  90  409  81.8   3.0
18  王冠廷  男   87  93   96  72  60  408  81.6   4.0
40  劉靜芬  女   82  83   98  71  72  406  81.2   5.0
32  蕭怡伶  女   84  66   93  70  91  404  80.8   6.0
15  王婉茹  女   61  85   80  87  86  399  79.8   7.0
1   劉彥宏  男   57  99   92  88  57  393  78.6   8.0
3   吳子睿  男   62  90   85  84  67  388  77.6   9.0
12  呂承恩  男   94  75   75  68  72  384  76.8  10.0
30  楊靜宜  女   69  89  100  63  62  383  76.6  11.0
25  洪怡君  女   70  84   84  70  74  382  76.4  12.0
20  莊子謙  男   90  44   97  63  87  381  76.2  13.0
22  李柏融  男   77  98   59  53  94  381  76.2  13.0
36  蕭浩宇  男  100  70   54  74  82  380  76.0  15.0
4   蕭志明  男   87  41   57  95  96  376  75.2  16.0
38  邱宗翰  男   93  61   79  42  98  373  74.6  17.0
2   曾彥廷  男   42  85  100  81  62  370  74.0  18.0
11  葉柏翰  男   50  89   89  64  75  367  73.4  19.0
8   羅淑芬  女   86  71   80  82  46  365  73.0  20.0
44  施子軒  男   93  88   90  43  49  363  72.6  21.0
31  曾靜儀  女   65  77   46  87  81  356  71.2  22.0
27  江雅琪  女   57  76   75  73  74  355  71.0  23.0
26  洪柏宏  男   73  66   76  82  58  355  71.0  23.0
24  呂佳瑩  女   89  41   78  67  79  354  70.8  25.0
19  呂婉慧  女   42  56   92  96  68  354  70.8  25.0
16  莊承翰  男   96  47   62  56  93  354  70.8  25.0
17  黃裕傑  男   92  80   97  44  40  353  70.6  28.0
13  蘇雅婷  女   40  68   87  74  79  348  69.6  29.0
41  許淑芬  女   94  66   53  75  50  338  67.6  30.0
29  簡婉慧  女   55  56   67  86  72  336  67.2  31.0
21  蘇彥宏  男   49  87   92  43  62  333  66.6  32.0
37  呂怡靜  女   66  47   75  92  49  329  65.8  33.0
23  曾明軒  男   58  50   54  79  87  328  65.6  34.0
50  詹柏翰  男   44  42   83  89  67  325  65.0  35.0
48  劉婉婷  女   59  76   41  80  69  325  65.0  35.0
33  洪裕豪  男   66  44   81  52  80  323  64.6  37.0
49  曾明哲  男   42  67   43  72  98  322  64.4  38.0
9   許美慧  女   55  78   54  68  64  319  63.8  39.0
47  周美玲  女   93  76   56  48  46  319  63.8  39.0
28  郭怡萱  女   67  67   94  41  47  316  63.2  41.0
5   王文傑  男   87  57   59  71  41  315  63.0  42.0
45  莊柏融  男   51  47   78  50  87  313  62.6  43.0
7   謝欣蓉  女   47  73   75  47  60  302  60.4  44.0
46  鍾浩銘  男   56  41   52  89  58  296  59.2  45.0
6   朱冠霖  男   54  55   61  44  75  289  57.8  46.0
42  邱裕豪  男   53  60   43  84  46  286  57.2  47.0
14  高浩宇  男   44  47   56  92  47  286  57.2  47.0
43  吳雅萍  女   66  42   44  84  42  278  55.6  49.0
10  廖志豪  男   59  44   56  47  53  259  51.8  50.0