In [25]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(40 ,101, size=(50,5))
#print(type(scores))
#print(scores.shape)
#scores
scores_df= pd.DataFrame(scores,
            index=range(1,51),
            columns=['國文','英文','數學','地理','歷史'])
#scores_df.T #樞紐分析
names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']]= names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名','性別','國文','英文','數學','地理','歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  62  44  43  49  54
7   謝欣蓉  女  91  80  96  57  57
8   羅淑芬  女  95  67  64  97  84
9   許美慧  女  95  55  69  91  40
10  廖志豪  男  77  82  49  81  57

In [26]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60")

     姓名 性別  國文  英文  數學  地理  歷史
13  蘇雅婷  女  58  68  56  68  87
15  王婉茹  女  42  46  78  88  58
27  江雅琪  女  41  94  83  71  79
29  簡婉慧  女  54  40  40  86  48

In [27]:
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df["總分"].rank(ascending=False,method='min')
scores_df.sort_values(by='排名')

     姓名 性別   國文  英文   數學  地理  歷史   總分    平均    排名
34  簡建宏  男   54  98   90  99  85  426  85.2   1.0
33  洪裕豪  男   96  99   62  81  71  409  81.8   2.0
8   羅淑芬  女   95  67   64  97  84  407  81.4   3.0
19  呂婉慧  女   85  83   92  91  52  403  80.6   4.0
39  彭美慧  女   97  96   92  59  56  400  80.0   5.0
17  黃裕傑  男   63  81   96  80  70  390  78.0   6.0
4   蕭志明  男   59  77   86  67  99  388  77.6   7.0
36  蕭浩宇  男   54  61   96  89  84  384  76.8   8.0
7   謝欣蓉  女   91  80   96  57  57  381  76.2   9.0
11  葉柏翰  男   43  93   69  93  76  374  74.8  10.0
40  劉靜芬  女  100  68   74  62  68  372  74.4  11.0
44  施子軒  男   82  51   81  92  63  369  73.8  12.0
27  江雅琪  女   41  94   83  71  79  368  73.6  13.0
37  呂怡靜  女   80  45   58  93  92  368  73.6  13.0
5   王文傑  男   64  62   93  97  51  367  73.4  15.0
32  蕭怡伶  女   67  85   50  69  91  362  72.4  16.0
12  呂承恩  男   42  42   91  92  94  361  72.2  17.0
22  李柏融  男   97  53  100  65  41  356  71.2  18.0
31  曾靜儀  女   64  89   83  47  71  354  70.8  19.0
42  邱裕豪  男   40  83   87  47  96  353  70.6  20.0
9   許美慧  女   95  55   69  91  40  350  70.0  21.0
26  洪柏宏  男   98  94   57  40  60  349  69.8  22.0
10  廖志豪  男   77  82   49  81  57  346  69.2  23.0
48  劉婉婷  女   85  61   66  69  63  344  68.8  24.0
45  莊柏融  男   53  61   92  88  49  343  68.6  25.0
20  莊子謙  男   77  99   47  64  56  343  68.6  25.0
41  許淑芬  女   99  60   77  50  56  342  68.4  27.0
13  蘇雅婷  女   58  68   56  68  87  337  67.4  28.0
46  鍾浩銘  男   60  57   61  74  81  333  66.6  29.0
21  蘇彥宏  男   67  42   81  95  48  333  66.6  29.0
47  周美玲  女   73  88   72  60  40  333  66.6  29.0
43  吳雅萍  女   80  68   52  66  65  331  66.2  32.0
25  洪怡君  女   72  42   83  44  89  330  66.0  33.0
14  高浩宇  男   53  91   53  86  42  325  65.0  34.0
38  邱宗翰  男   78  53   68  62  63  324  64.8  35.0
50  詹柏翰  男   89  48   41  51  93  322  64.4  36.0
1   劉彥宏  男   62  70   73  52  60  317  63.4  37.0
15  王婉茹  女   42  46   78  88  58  312  62.4  38.0
35  劉浩然  男   68  81   66  43  53  311  62.2  39.0
2   曾彥廷  男   96  40   45  85  45  311  62.2  39.0
28  郭怡萱  女   62  46   44  67  90  309  61.8  41.0
30  楊靜宜  女   62  59   83  57  46  307  61.4  42.0
16  莊承翰  男   60  54   47  68  74  303  60.6  43.0
18  王冠廷  男   67  60   89  41  43  300  60.0  44.0
23  曾明軒  男   52  45   70  72  42  281  56.2  45.0
24  呂佳瑩  女   89  48   44  60  40  281  56.2  45.0
3   吳子睿  男   48  44   40  87  54  273  54.6  47.0
49  曾明哲  男   51  49   48  49  76  273  54.6  47.0
29  簡婉慧  女   54  40   40  86  48  268  53.6  49.0
6   朱冠霖  男   62  44   43  49  54  252  50.4  50.0

In [31]:
from pandas import Series
def calulate(s:Series)-> int:
    n = (s < 60).sum()
    return n
    
scores_df['及格的科目數'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(calulate,axis=1)
scores_df

     姓名 性別   國文  英文   數學  地理  歷史   總分    平均    排名  及格的科目數
1   劉彥宏  男   62  70   73  52  60  317  63.4  37.0       1
2   曾彥廷  男   96  40   45  85  45  311  62.2  39.0       3
3   吳子睿  男   48  44   40  87  54  273  54.6  47.0       4
4   蕭志明  男   59  77   86  67  99  388  77.6   7.0       1
5   王文傑  男   64  62   93  97  51  367  73.4  15.0       1
6   朱冠霖  男   62  44   43  49  54  252  50.4  50.0       4
7   謝欣蓉  女   91  80   96  57  57  381  76.2   9.0       2
8   羅淑芬  女   95  67   64  97  84  407  81.4   3.0       0
9   許美慧  女   95  55   69  91  40  350  70.0  21.0       2
10  廖志豪  男   77  82   49  81  57  346  69.2  23.0       2
11  葉柏翰  男   43  93   69  93  76  374  74.8  10.0       1
12  呂承恩  男   42  42   91  92  94  361  72.2  17.0       2
13  蘇雅婷  女   58  68   56  68  87  337  67.4  28.0       2
14  高浩宇  男   53  91   53  86  42  325  65.0  34.0       3
15  王婉茹  女   42  46   78  88  58  312  62.4  38.0       3
16  莊承翰  男   60  54   47  68  74  303  60.6  43.0       2
17  黃裕傑  男   63  81   96  80  70  390  78.0   6.0       0
18  王冠廷  男   67  60   89  41  43  300  60.0  44.0       2
19  呂婉慧  女   85  83   92  91  52  403  80.6   4.0       1
20  莊子謙  男   77  99   47  64  56  343  68.6  25.0       2
21  蘇彥宏  男   67  42   81  95  48  333  66.6  29.0       2
22  李柏融  男   97  53  100  65  41  356  71.2  18.0       2
23  曾明軒  男   52  45   70  72  42  281  56.2  45.0       3
24  呂佳瑩  女   89  48   44  60  40  281  56.2  45.0       3
25  洪怡君  女   72  42   83  44  89  330  66.0  33.0       2
26  洪柏宏  男   98  94   57  40  60  349  69.8  22.0       2
27  江雅琪  女   41  94   83  71  79  368  73.6  13.0       1
28  郭怡萱  女   62  46   44  67  90  309  61.8  41.0       2
29  簡婉慧  女   54  40   40  86  48  268  53.6  49.0       4
30  楊靜宜  女   62  59   83  57  46  307  61.4  42.0       3
31  曾靜儀  女   64  89   83  47  71  354  70.8  19.0       1
32  蕭怡伶  女   67  85   50  69  91  362  72.4  16.0       1
33  洪裕豪  男   96  99   62  81  71  409  81.8   2.0       0
34  簡建宏  男   54  98   90  99  85  426  85.2   1.0       1
35  劉浩然  男   68  81   66  43  53  311  62.2  39.0       2
36  蕭浩宇  男   54  61   96  89  84  384  76.8   8.0       1
37  呂怡靜  女   80  45   58  93  92  368  73.6  13.0       2
38  邱宗翰  男   78  53   68  62  63  324  64.8  35.0       1
39  彭美慧  女   97  96   92  59  56  400  80.0   5.0       2
40  劉靜芬  女  100  68   74  62  68  372  74.4  11.0       0
41  許淑芬  女   99  60   77  50  56  342  68.4  27.0       2
42  邱裕豪  男   40  83   87  47  96  353  70.6  20.0       2
43  吳雅萍  女   80  68   52  66  65  331  66.2  32.0       1
44  施子軒  男   82  51   81  92  63  369  73.8  12.0       1
45  莊柏融  男   53  61   92  88  49  343  68.6  25.0       2
46  鍾浩銘  男   60  57   61  74  81  333  66.6  29.0       1
47  周美玲  女   73  88   72  60  40  333  66.6  29.0       1
48  劉婉婷  女   85  61   66  69  63  344  68.8  24.0       0
49  曾明哲  男   51  49   48  49  76  273  54.6  47.0       4
50  詹柏翰  男   89  48   41  51  93  322  64.4  36.0       3