In [16]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(40 ,101, size=(50,5))
#print(type(scores))
#print(scores.shape)
#scores
scores_df= pd.DataFrame(scores,
            index=range(1,51),
            columns=['國文','英文','數學','地理','歷史'])
#scores_df.T #樞紐分析
names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']]= names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名','性別','國文','英文','數學','地理','歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  54  55  61  44  75
7   謝欣蓉  女  47  73  75  47  60
8   羅淑芬  女  86  71  80  82  46
9   許美慧  女  55  78  54  68  64
10  廖志豪  男  59  44  56  47  53

In [21]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]

     姓名 性別  國文  英文   數學  地理  歷史
1   劉彥宏  男  57  99   92  88  57
2   曾彥廷  男  42  85  100  81  62
6   朱冠霖  男  54  55   61  44  75
7   謝欣蓉  女  47  73   75  47  60
9   許美慧  女  55  78   54  68  64
10  廖志豪  男  59  44   56  47  53
11  葉柏翰  男  50  89   89  64  75
13  蘇雅婷  女  40  68   87  74  79
14  高浩宇  男  44  47   56  92  47
19  呂婉慧  女  42  56   92  96  68
21  蘇彥宏  男  49  87   92  43  62
23  曾明軒  男  58  50   54  79  87
27  江雅琪  女  57  76   75  73  74
29  簡婉慧  女  55  56   67  86  72
42  邱裕豪  男  53  60   43  84  46
45  莊柏融  男  51  47   78  50  87
46  鍾浩銘  男  56  41   52  89  58
48  劉婉婷  女  59  76   41  80  69
49  曾明哲  男  42  67   43  72  98
50  詹柏翰  男  44  42   83  89  67